apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: openshift-gitops
spec:
  destination:
    namespace: spring-test-application
    server: 'https://kubernetes.default.svc'
  ignoreDifferences:
    - group: apps
      jsonPointers:
        - /spec/template/spec/containers
      kind: Deployment
  project: devopsdt
  source:
    path: ./k8s
    repoURL: >-
      https://github.com/yongdoohar/oc-cicd-demo.git
    targetRevision: main
    directory:
      recurse: true
