kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: demo
  namespace: spring-test-application
  labels:
    app: demo
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'demo:latest'
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
    type: Docker
  postCommit: {}
  source:
    git:
      uri: https://github.com/yongdoohar/oc-cicd-demo.git
  runPolicy: Serial
