apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: demo
  namespace: spring-test-application
  labels:
    app: demo
spec:
  params:
    - default: demo
      name: IMAGE_NAME
      type: string
    - default: https://github.com/yongdoohar/oc-cicd-demo.git
      name: GIT_REPO
      type: string
    - default: main
      name: GIT_REVISION
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: maven-build
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: maven-build
      workspaces:
        - name: source
          workspace: workspace
        - name: m2
          workspace: maven-cache
        - name: setting
          workspace: setting
    - name: deploy
      params:   
        - name: ARGS
          value:
            - oc start-build demo --from-dir /tmp/src
      runAfter:
        - maven-build
      taskRef:
        kind: Task
        name: openshift-cli-workspaces
      workspaces:
        - name: source
          workspace: workspace
  workspaces:
    - name: workspace
    - name: maven-cache
    - name: setting

